name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/azureuser/myapp
            git pull
            sudo pkill node || true
            sudo node app.js > output.log 2>&1 &
